En utilisant numpy:

Ex 1 :Addition
Écrire un programme pour lire les éléments de deux matrices et ajoutez les deux matrices dans la troisième.

La somme de deux matrices de taille (m,n), $(A_{ij}) et (B_{ij}) notée $A+B$  est à nouveau une matrice (C_{ij}) de taille (m,n), obtenue en additionnant les éléments correspondants: $c_{ij}=a_{ij}+b_{ij}$


In [3]:
import numpy 
 
A = numpy.array([ [5, 7, 4], [0, 2, 0], [0, 3, 10] ])
B = numpy.array([ [1, -1, 1], [2, 1, 4], [12, 7, 20] ])
 
C = A + B
 
print("La matrice A : \n", A)
print("La matrice B : \n", B)
print("La matrice A + B : \n", C)


La matrice A : 
 [[ 5  7  4]
 [ 0  2  0]
 [ 0  3 10]]
La matrice B : 
 [[ 1 -1  1]
 [ 2  1  4]
 [12  7 20]]
La matrice A + B : 
 [[ 6  6  5]
 [ 2  3  4]
 [12 10 30]]


Ex2 :Multiplication
Écrire un programme pour lire les éléments de deux matrices, puis multipliez les deux matrices dans la troisième.

Deux matrices ne peuvent être multipliées que si le nombre de colonnes de la première matrice est le même que le nombre de lignes de la seconde matrice.

Si $ A=(a_{ij})$ est une matrice de taille (m,n), $ B=(b_{ij})$ et est une matrice de taille (n,p), alors leur produit, noté $AB=(c_{ij})$ est une matrice de taille (m,p) définie par :
$$\forall i,j : c_{ij}=\sum_{k=i}^{n} a_{ik}*b_{kj}$$

In [5]:
import numpy 
 
A = numpy.array([ [5, 7, 4], [0, 2, 0], [0, 3, 10] ])
B = numpy.array([ [1, -1, 1], [2, 1, 4], [12, 7, 20] ])
 
C = A.dot(B)
 
print("La matrice A : \n", A)
print("La matrice B : \n", B)
print("La matrice A * B : \n", C)

La matrice A : 
 [[ 5  7  4]
 [ 0  2  0]
 [ 0  3 10]]
La matrice B : 
 [[ 1 -1  1]
 [ 2  1  4]
 [12  7 20]]
La matrice A * B : 
 [[ 67  30 113]
 [  4   2   8]
 [126  73 212]]


Ex 3: Matrice de Markov

Une matrice de Markov est une matrice carrée dont chaque élément est un réel compris entre 0 et 1 et dont la somme des éléments de chaque ligne vaut 1. Cela correspond, en probabilité, à la matrice de transition d'une chaîne de Markov finie.

Une matrice est dite bistochastique (ou doublement stochastique) si la somme des éléments de chaque ligne et de chaque colonne vaut 1.

1. Ecrire une fonction eststochastique(P) qui permet de vérifier est ce que la matrice P est stochastique ou non
2. Ecrire une fonction estbistochastique(P) qui permet de vérifier est ce que la matrice P est bistochastique ou non
3. Ecrire une fonction vecteurstable(G, h) qui permet de vérifier est ce que h est un vecteur stable de G ou non



In [13]:
def eststochastique(P):
    nblignes = len(P)  
    nbcolonnes = len(P[0])  
 
    stochastique = True  
    for i in range(nblignes):
        s = 0
        for j in range(nbcolonnes):
            s += P[i][j]
        if s > 1:
            stochastique = False
            break
    return stochastique

def estbistochastique(P):
    nblignes = len(P)  
    nbcolonnes = len(P[0])  
 
    bistochastique = True  
    if(eststochastique(P)):
      for j in range(nbcolonnes):
          s = 0
          for i in range(nblignes):
              s += P[i][j]
          if s > 1:
              bistochastique = False
              break
    return bistochastique

def vecteurstable(G, h):
    nblignes = len(G)  
    nbcolonnes = len(G[0])  
    vecteurstable = True
    if(eststochastique(G)):
        for j in range(nbcolonnes):
            s = 0
            for i in range(nblignes):
                s += h[i]*G[i][j]
            if s != h[j]:
                vecteurstable = False
                break
    else:
        vecteurstable = False
    return vecteurstable    





Ex 4: Transposer

Programmer une fonction qui, étant donné une matrice à deux dimensions A, retourne lamatrice B dont la première colonne est la première ligne de A, la seconde la deuxième ligne de A, etc. B s’appelle la transposée de A.

In [14]:
import numpy as np
 
A = numpy.array([ [5, 7, 4], [0, 2, 0], [0, 3, 10] ])
 
B = A.transpose()
 
print("A : \n", A)
print("La transposée de A : \n", B)

A : 
 [[ 5  7  4]
 [ 0  2  0]
 [ 0  3 10]]
La transposée de A : 
 [[ 5  0  0]
 [ 7  2  3]
 [ 4  0 10]]


Ex 5: Permutations
1. $M$ désignant une matrice quelconque d’entiers à $l_i$ lignes et $co$ colonnes, $n$ un entier quelconque, programmer une fonction qui retourne la matrice $Sortie$ qui empile verticalement les $co+1$ matrices obtenues en adjoignant à $M$ une colonne $A$ à $li$ lignes dont tousles éléments sont égaux à $n$, $A$ étant placée d’abord devant $M$, puis entre la première et deuxième colonne de $M^a$,etc, jusqu’à ce que $A$ devienne sa dernière colonne. La matriceobtenue  aura $co+1$ colonnes et $(n+1)$ $li$ lignes

2. Écrire toutes les permutations de(1, ..., n)